### ISSUE TITLE
Network error when starting up sip-creator 1.1.0 on windows 10

### ISSUE THREAD

**Issue by kiivihal** [delving/sip-creator#488]
When you start the sip-creator jar 1.1.0 on windows 10 you get the following error.

> 
> C:\Users\XXXXX>java -jar C:\Users\XXXX\Downloads\sip-app-1.1.0-exe=
> jar.jar
> Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.net=
> .MalformedURLException: no protocol:
>         at eu.delving.sip.base.NetworkClient.<init>(NetworkClient.java:146)
>         at eu.delving.sip.Application.<init>(Application.java:143)
>         at eu.delving.sip.Application.<init>(Application.java:92)
>         at eu.delving.sip.Application$LaunchAction.run(Application.java:382=
> )
>         at java.awt.event.InvocationEvent.dispatch(Unknown Source)
>         at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
>         at java.awt.EventQueue.access$500(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.awt.EventQueue$3.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersec=
> tionPrivilege(Unknown Source)
>         at java.awt.EventQueue.dispatchEvent(Unknown Source)
>         at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Sour=
> ce)
>         at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Sour=
> ce)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
>         at java.awt.EventDispatchThread.run(Unknown Source)
> Caused by: java.net.MalformedURLException: no protocol:

When sip-creator 1.0.9 is started on the same machine the error does not occur.

**Comment by kiivihal** [comment]
The issue was caused by the fact that no default was set when the Java preferences was not initialised.
